version: '3'

services:
  fastapi:
    build: back_end/
    environment:
      - USER_NAME=${USER_NAME}
      - PASSWORD=${PASSWORD}
      - URL=${URL}
    ports:
      - 8000:8000
    networks:
      - bg_rec_network
    container_name: fastapi
  streamlit:
    build: front_end/
    depends_on:
      - fastapi
    ports:
      - 8501:8501
    networks:
      - bg_rec_network
    container_name: streamlit

networks:
  bg_rec_network:
    driver: bridge
    